// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fir_rpc.proto

package com.yunhui.fir.rpc.proto;

public final class FirRpcProtocol {
  private FirRpcProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.dousi.codec.RpcStatus}
   */
  public enum RpcStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * OK;
     * </pre>
     *
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <pre>
     * Outer error;
     * </pre>
     *
     * <code>OUTER_ERROR = 1;</code>
     */
    OUTER_ERROR(1),
    /**
     * <pre>
     * Inner error;
     * </pre>
     *
     * <code>INNER_ERROR = 2;</code>
     */
    INNER_ERROR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * OK;
     * </pre>
     *
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <pre>
     * Outer error;
     * </pre>
     *
     * <code>OUTER_ERROR = 1;</code>
     */
    public static final int OUTER_ERROR_VALUE = 1;
    /**
     * <pre>
     * Inner error;
     * </pre>
     *
     * <code>INNER_ERROR = 2;</code>
     */
    public static final int INNER_ERROR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RpcStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RpcStatus forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return OUTER_ERROR;
        case 2: return INNER_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RpcStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RpcStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RpcStatus>() {
            public RpcStatus findValueByNumber(int number) {
              return RpcStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.yunhui.fir.rpc.proto.FirRpcProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final RpcStatus[] VALUES = values();

    public static RpcStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RpcStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.dousi.codec.RpcStatus)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.dousi.codec.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 requestId = 1;</code>
     * @return The requestId.
     */
    long getRequestId();

    /**
     * <code>string interfaceName = 2;</code>
     * @return The interfaceName.
     */
    java.lang.String getInterfaceName();
    /**
     * <code>string interfaceName = 2;</code>
     * @return The bytes for interfaceName.
     */
    com.google.protobuf.ByteString
        getInterfaceNameBytes();

    /**
     * <code>string methodName = 3;</code>
     * @return The methodName.
     */
    java.lang.String getMethodName();
    /**
     * <code>string methodName = 3;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated .google.protobuf.Any args = 5;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getArgsList();
    /**
     * <code>repeated .google.protobuf.Any args = 5;</code>
     */
    com.google.protobuf.Any getArgs(int index);
    /**
     * <code>repeated .google.protobuf.Any args = 5;</code>
     */
    int getArgsCount();
    /**
     * <code>repeated .google.protobuf.Any args = 5;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getArgsOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Any args = 5;</code>
     */
    com.google.protobuf.AnyOrBuilder getArgsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.dousi.codec.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.dousi.codec.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      interfaceName_ = "";
      methodName_ = "";
      args_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              requestId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              interfaceName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                args_ = new java.util.ArrayList<com.google.protobuf.Any>();
                mutable_bitField0_ |= 0x00000001;
              }
              args_.add(
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          args_ = java.util.Collections.unmodifiableList(args_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yunhui.fir.rpc.proto.FirRpcProtocol.internal_static_org_dousi_codec_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yunhui.fir.rpc.proto.FirRpcProtocol.internal_static_org_dousi_codec_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yunhui.fir.rpc.proto.FirRpcProtocol.Request.class, com.yunhui.fir.rpc.proto.FirRpcProtocol.Request.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <code>int64 requestId = 1;</code>
     * @return The requestId.
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int INTERFACENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object interfaceName_;
    /**
     * <code>string interfaceName = 2;</code>
     * @return The interfaceName.
     */
    public java.lang.String getInterfaceName() {
      java.lang.Object ref = interfaceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interfaceName_ = s;
        return s;
      }
    }
    /**
     * <code>string interfaceName = 2;</code>
     * @return The bytes for interfaceName.
     */
    public com.google.protobuf.ByteString
        getInterfaceNameBytes() {
      java.lang.Object ref = interfaceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interfaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object methodName_;
    /**
     * <code>string methodName = 3;</code>
     * @return The methodName.
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string methodName = 3;</code>
     * @return The bytes for methodName.
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGS_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.Any> args_;
    /**
     * <code>repeated .google.protobuf.Any args = 5;</code>
     */
    public java.util.List<com.google.protobuf.Any> getArgsList() {
      return args_;
    }
    /**
     * <code>repeated .google.protobuf.Any args = 5;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getArgsOrBuilderList() {
      return args_;
    }
    /**
     * <code>repeated .google.protobuf.Any args = 5;</code>
     */
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <code>repeated .google.protobuf.Any args = 5;</code>
     */
    public com.google.protobuf.Any getArgs(int index) {
      return args_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Any args = 5;</code>
     */
    public com.google.protobuf.AnyOrBuilder getArgsOrBuilder(
        int index) {
      return args_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeInt64(1, requestId_);
      }
      if (!getInterfaceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, interfaceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, methodName_);
      }
      for (int i = 0; i < args_.size(); i++) {
        output.writeMessage(5, args_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      if (!getInterfaceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, interfaceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, methodName_);
      }
      for (int i = 0; i < args_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, args_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yunhui.fir.rpc.proto.FirRpcProtocol.Request)) {
        return super.equals(obj);
      }
      com.yunhui.fir.rpc.proto.FirRpcProtocol.Request other = (com.yunhui.fir.rpc.proto.FirRpcProtocol.Request) obj;

      if (getRequestId()
          != other.getRequestId()) return false;
      if (!getInterfaceName()
          .equals(other.getInterfaceName())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getArgsList()
          .equals(other.getArgsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + INTERFACENAME_FIELD_NUMBER;
      hash = (53 * hash) + getInterfaceName().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getArgsCount() > 0) {
        hash = (37 * hash) + ARGS_FIELD_NUMBER;
        hash = (53 * hash) + getArgsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yunhui.fir.rpc.proto.FirRpcProtocol.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.dousi.codec.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.dousi.codec.Request)
        com.yunhui.fir.rpc.proto.FirRpcProtocol.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yunhui.fir.rpc.proto.FirRpcProtocol.internal_static_org_dousi_codec_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yunhui.fir.rpc.proto.FirRpcProtocol.internal_static_org_dousi_codec_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yunhui.fir.rpc.proto.FirRpcProtocol.Request.class, com.yunhui.fir.rpc.proto.FirRpcProtocol.Request.Builder.class);
      }

      // Construct using com.yunhui.fir.rpc.proto.FirRpcProtocol.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArgsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = 0L;

        interfaceName_ = "";

        methodName_ = "";

        if (argsBuilder_ == null) {
          args_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          argsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yunhui.fir.rpc.proto.FirRpcProtocol.internal_static_org_dousi_codec_Request_descriptor;
      }

      @java.lang.Override
      public com.yunhui.fir.rpc.proto.FirRpcProtocol.Request getDefaultInstanceForType() {
        return com.yunhui.fir.rpc.proto.FirRpcProtocol.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.yunhui.fir.rpc.proto.FirRpcProtocol.Request build() {
        com.yunhui.fir.rpc.proto.FirRpcProtocol.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yunhui.fir.rpc.proto.FirRpcProtocol.Request buildPartial() {
        com.yunhui.fir.rpc.proto.FirRpcProtocol.Request result = new com.yunhui.fir.rpc.proto.FirRpcProtocol.Request(this);
        int from_bitField0_ = bitField0_;
        result.requestId_ = requestId_;
        result.interfaceName_ = interfaceName_;
        result.methodName_ = methodName_;
        if (argsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            args_ = java.util.Collections.unmodifiableList(args_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.args_ = args_;
        } else {
          result.args_ = argsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yunhui.fir.rpc.proto.FirRpcProtocol.Request) {
          return mergeFrom((com.yunhui.fir.rpc.proto.FirRpcProtocol.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yunhui.fir.rpc.proto.FirRpcProtocol.Request other) {
        if (other == com.yunhui.fir.rpc.proto.FirRpcProtocol.Request.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (!other.getInterfaceName().isEmpty()) {
          interfaceName_ = other.interfaceName_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (argsBuilder_ == null) {
          if (!other.args_.isEmpty()) {
            if (args_.isEmpty()) {
              args_ = other.args_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureArgsIsMutable();
              args_.addAll(other.args_);
            }
            onChanged();
          }
        } else {
          if (!other.args_.isEmpty()) {
            if (argsBuilder_.isEmpty()) {
              argsBuilder_.dispose();
              argsBuilder_ = null;
              args_ = other.args_;
              bitField0_ = (bitField0_ & ~0x00000001);
              argsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArgsFieldBuilder() : null;
            } else {
              argsBuilder_.addAllMessages(other.args_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yunhui.fir.rpc.proto.FirRpcProtocol.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yunhui.fir.rpc.proto.FirRpcProtocol.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long requestId_ ;
      /**
       * <code>int64 requestId = 1;</code>
       * @return The requestId.
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>int64 requestId = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object interfaceName_ = "";
      /**
       * <code>string interfaceName = 2;</code>
       * @return The interfaceName.
       */
      public java.lang.String getInterfaceName() {
        java.lang.Object ref = interfaceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interfaceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string interfaceName = 2;</code>
       * @return The bytes for interfaceName.
       */
      public com.google.protobuf.ByteString
          getInterfaceNameBytes() {
        java.lang.Object ref = interfaceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interfaceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string interfaceName = 2;</code>
       * @param value The interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interfaceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string interfaceName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterfaceName() {
        
        interfaceName_ = getDefaultInstance().getInterfaceName();
        onChanged();
        return this;
      }
      /**
       * <code>string interfaceName = 2;</code>
       * @param value The bytes for interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interfaceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string methodName = 3;</code>
       * @return The methodName.
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string methodName = 3;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string methodName = 3;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Any> args_ =
        java.util.Collections.emptyList();
      private void ensureArgsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          args_ = new java.util.ArrayList<com.google.protobuf.Any>(args_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> argsBuilder_;

      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public java.util.List<com.google.protobuf.Any> getArgsList() {
        if (argsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(args_);
        } else {
          return argsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public int getArgsCount() {
        if (argsBuilder_ == null) {
          return args_.size();
        } else {
          return argsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public com.google.protobuf.Any getArgs(int index) {
        if (argsBuilder_ == null) {
          return args_.get(index);
        } else {
          return argsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public Builder setArgs(
          int index, com.google.protobuf.Any value) {
        if (argsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgsIsMutable();
          args_.set(index, value);
          onChanged();
        } else {
          argsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public Builder setArgs(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (argsBuilder_ == null) {
          ensureArgsIsMutable();
          args_.set(index, builderForValue.build());
          onChanged();
        } else {
          argsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public Builder addArgs(com.google.protobuf.Any value) {
        if (argsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgsIsMutable();
          args_.add(value);
          onChanged();
        } else {
          argsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public Builder addArgs(
          int index, com.google.protobuf.Any value) {
        if (argsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgsIsMutable();
          args_.add(index, value);
          onChanged();
        } else {
          argsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public Builder addArgs(
          com.google.protobuf.Any.Builder builderForValue) {
        if (argsBuilder_ == null) {
          ensureArgsIsMutable();
          args_.add(builderForValue.build());
          onChanged();
        } else {
          argsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public Builder addArgs(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (argsBuilder_ == null) {
          ensureArgsIsMutable();
          args_.add(index, builderForValue.build());
          onChanged();
        } else {
          argsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public Builder addAllArgs(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        if (argsBuilder_ == null) {
          ensureArgsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, args_);
          onChanged();
        } else {
          argsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public Builder clearArgs() {
        if (argsBuilder_ == null) {
          args_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          argsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public Builder removeArgs(int index) {
        if (argsBuilder_ == null) {
          ensureArgsIsMutable();
          args_.remove(index);
          onChanged();
        } else {
          argsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public com.google.protobuf.Any.Builder getArgsBuilder(
          int index) {
        return getArgsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public com.google.protobuf.AnyOrBuilder getArgsOrBuilder(
          int index) {
        if (argsBuilder_ == null) {
          return args_.get(index);  } else {
          return argsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getArgsOrBuilderList() {
        if (argsBuilder_ != null) {
          return argsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(args_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public com.google.protobuf.Any.Builder addArgsBuilder() {
        return getArgsFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public com.google.protobuf.Any.Builder addArgsBuilder(
          int index) {
        return getArgsFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any args = 5;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getArgsBuilderList() {
        return getArgsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getArgsFieldBuilder() {
        if (argsBuilder_ == null) {
          argsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  args_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          args_ = null;
        }
        return argsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.dousi.codec.Request)
    }

    // @@protoc_insertion_point(class_scope:org.dousi.codec.Request)
    private static final com.yunhui.fir.rpc.proto.FirRpcProtocol.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yunhui.fir.rpc.proto.FirRpcProtocol.Request();
    }

    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yunhui.fir.rpc.proto.FirRpcProtocol.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.dousi.codec.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 requestId = 1;</code>
     * @return The requestId.
     */
    long getRequestId();

    /**
     * <code>.org.dousi.codec.RpcStatus status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.org.dousi.codec.RpcStatus status = 2;</code>
     * @return The status.
     */
    com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus getStatus();

    /**
     * <code>.google.protobuf.Any result = 3;</code>
     * @return Whether the result field is set.
     */
    boolean hasResult();
    /**
     * <code>.google.protobuf.Any result = 3;</code>
     * @return The result.
     */
    com.google.protobuf.Any getResult();
    /**
     * <code>.google.protobuf.Any result = 3;</code>
     */
    com.google.protobuf.AnyOrBuilder getResultOrBuilder();

    /**
     * <code>string errorMessage = 4;</code>
     * @return The errorMessage.
     */
    java.lang.String getErrorMessage();
    /**
     * <code>string errorMessage = 4;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    public com.yunhui.fir.rpc.proto.FirRpcProtocol.Response.ReturnValueCase getReturnValueCase();
  }
  /**
   * Protobuf type {@code org.dousi.codec.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.dousi.codec.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              requestId_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 26: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (returnValueCase_ == 3) {
                subBuilder = ((com.google.protobuf.Any) returnValue_).toBuilder();
              }
              returnValue_ =
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.protobuf.Any) returnValue_);
                returnValue_ = subBuilder.buildPartial();
              }
              returnValueCase_ = 3;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              returnValueCase_ = 4;
              returnValue_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yunhui.fir.rpc.proto.FirRpcProtocol.internal_static_org_dousi_codec_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yunhui.fir.rpc.proto.FirRpcProtocol.internal_static_org_dousi_codec_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yunhui.fir.rpc.proto.FirRpcProtocol.Response.class, com.yunhui.fir.rpc.proto.FirRpcProtocol.Response.Builder.class);
    }

    private int returnValueCase_ = 0;
    private java.lang.Object returnValue_;
    public enum ReturnValueCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      RESULT(3),
      ERRORMESSAGE(4),
      RETURNVALUE_NOT_SET(0);
      private final int value;
      private ReturnValueCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ReturnValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ReturnValueCase forNumber(int value) {
        switch (value) {
          case 3: return RESULT;
          case 4: return ERRORMESSAGE;
          case 0: return RETURNVALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ReturnValueCase
    getReturnValueCase() {
      return ReturnValueCase.forNumber(
          returnValueCase_);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <code>int64 requestId = 1;</code>
     * @return The requestId.
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>.org.dousi.codec.RpcStatus status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.org.dousi.codec.RpcStatus status = 2;</code>
     * @return The status.
     */
    public com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus result = com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus.valueOf(status_);
      return result == null ? com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus.UNRECOGNIZED : result;
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    /**
     * <code>.google.protobuf.Any result = 3;</code>
     * @return Whether the result field is set.
     */
    public boolean hasResult() {
      return returnValueCase_ == 3;
    }
    /**
     * <code>.google.protobuf.Any result = 3;</code>
     * @return The result.
     */
    public com.google.protobuf.Any getResult() {
      if (returnValueCase_ == 3) {
         return (com.google.protobuf.Any) returnValue_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }
    /**
     * <code>.google.protobuf.Any result = 3;</code>
     */
    public com.google.protobuf.AnyOrBuilder getResultOrBuilder() {
      if (returnValueCase_ == 3) {
         return (com.google.protobuf.Any) returnValue_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 4;
    /**
     * <code>string errorMessage = 4;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = "";
      if (returnValueCase_ == 4) {
        ref = returnValue_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (returnValueCase_ == 4) {
          returnValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string errorMessage = 4;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = "";
      if (returnValueCase_ == 4) {
        ref = returnValue_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (returnValueCase_ == 4) {
          returnValue_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeInt64(1, requestId_);
      }
      if (status_ != com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus.OK.getNumber()) {
        output.writeEnum(2, status_);
      }
      if (returnValueCase_ == 3) {
        output.writeMessage(3, (com.google.protobuf.Any) returnValue_);
      }
      if (returnValueCase_ == 4) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, returnValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      if (status_ != com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (returnValueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.google.protobuf.Any) returnValue_);
      }
      if (returnValueCase_ == 4) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, returnValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yunhui.fir.rpc.proto.FirRpcProtocol.Response)) {
        return super.equals(obj);
      }
      com.yunhui.fir.rpc.proto.FirRpcProtocol.Response other = (com.yunhui.fir.rpc.proto.FirRpcProtocol.Response) obj;

      if (getRequestId()
          != other.getRequestId()) return false;
      if (status_ != other.status_) return false;
      if (!getReturnValueCase().equals(other.getReturnValueCase())) return false;
      switch (returnValueCase_) {
        case 3:
          if (!getResult()
              .equals(other.getResult())) return false;
          break;
        case 4:
          if (!getErrorMessage()
              .equals(other.getErrorMessage())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      switch (returnValueCase_) {
        case 3:
          hash = (37 * hash) + RESULT_FIELD_NUMBER;
          hash = (53 * hash) + getResult().hashCode();
          break;
        case 4:
          hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getErrorMessage().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yunhui.fir.rpc.proto.FirRpcProtocol.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.dousi.codec.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.dousi.codec.Response)
        com.yunhui.fir.rpc.proto.FirRpcProtocol.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yunhui.fir.rpc.proto.FirRpcProtocol.internal_static_org_dousi_codec_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yunhui.fir.rpc.proto.FirRpcProtocol.internal_static_org_dousi_codec_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yunhui.fir.rpc.proto.FirRpcProtocol.Response.class, com.yunhui.fir.rpc.proto.FirRpcProtocol.Response.Builder.class);
      }

      // Construct using com.yunhui.fir.rpc.proto.FirRpcProtocol.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = 0L;

        status_ = 0;

        returnValueCase_ = 0;
        returnValue_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yunhui.fir.rpc.proto.FirRpcProtocol.internal_static_org_dousi_codec_Response_descriptor;
      }

      @java.lang.Override
      public com.yunhui.fir.rpc.proto.FirRpcProtocol.Response getDefaultInstanceForType() {
        return com.yunhui.fir.rpc.proto.FirRpcProtocol.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.yunhui.fir.rpc.proto.FirRpcProtocol.Response build() {
        com.yunhui.fir.rpc.proto.FirRpcProtocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yunhui.fir.rpc.proto.FirRpcProtocol.Response buildPartial() {
        com.yunhui.fir.rpc.proto.FirRpcProtocol.Response result = new com.yunhui.fir.rpc.proto.FirRpcProtocol.Response(this);
        result.requestId_ = requestId_;
        result.status_ = status_;
        if (returnValueCase_ == 3) {
          if (resultBuilder_ == null) {
            result.returnValue_ = returnValue_;
          } else {
            result.returnValue_ = resultBuilder_.build();
          }
        }
        if (returnValueCase_ == 4) {
          result.returnValue_ = returnValue_;
        }
        result.returnValueCase_ = returnValueCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yunhui.fir.rpc.proto.FirRpcProtocol.Response) {
          return mergeFrom((com.yunhui.fir.rpc.proto.FirRpcProtocol.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yunhui.fir.rpc.proto.FirRpcProtocol.Response other) {
        if (other == com.yunhui.fir.rpc.proto.FirRpcProtocol.Response.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        switch (other.getReturnValueCase()) {
          case RESULT: {
            mergeResult(other.getResult());
            break;
          }
          case ERRORMESSAGE: {
            returnValueCase_ = 4;
            returnValue_ = other.returnValue_;
            onChanged();
            break;
          }
          case RETURNVALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yunhui.fir.rpc.proto.FirRpcProtocol.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yunhui.fir.rpc.proto.FirRpcProtocol.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int returnValueCase_ = 0;
      private java.lang.Object returnValue_;
      public ReturnValueCase
          getReturnValueCase() {
        return ReturnValueCase.forNumber(
            returnValueCase_);
      }

      public Builder clearReturnValue() {
        returnValueCase_ = 0;
        returnValue_ = null;
        onChanged();
        return this;
      }


      private long requestId_ ;
      /**
       * <code>int64 requestId = 1;</code>
       * @return The requestId.
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>int64 requestId = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.org.dousi.codec.RpcStatus status = 2;</code>
       * @return The enum numeric value on the wire for status.
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.org.dousi.codec.RpcStatus status = 2;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.dousi.codec.RpcStatus status = 2;</code>
       * @return The status.
       */
      public com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus getStatus() {
        @SuppressWarnings("deprecation")
        com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus result = com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus.valueOf(status_);
        return result == null ? com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.dousi.codec.RpcStatus status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.yunhui.fir.rpc.proto.FirRpcProtocol.RpcStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.dousi.codec.RpcStatus status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> resultBuilder_;
      /**
       * <code>.google.protobuf.Any result = 3;</code>
       * @return Whether the result field is set.
       */
      public boolean hasResult() {
        return returnValueCase_ == 3;
      }
      /**
       * <code>.google.protobuf.Any result = 3;</code>
       * @return The result.
       */
      public com.google.protobuf.Any getResult() {
        if (resultBuilder_ == null) {
          if (returnValueCase_ == 3) {
            return (com.google.protobuf.Any) returnValue_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        } else {
          if (returnValueCase_ == 3) {
            return resultBuilder_.getMessage();
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any result = 3;</code>
       */
      public Builder setResult(com.google.protobuf.Any value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          returnValue_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        returnValueCase_ = 3;
        return this;
      }
      /**
       * <code>.google.protobuf.Any result = 3;</code>
       */
      public Builder setResult(
          com.google.protobuf.Any.Builder builderForValue) {
        if (resultBuilder_ == null) {
          returnValue_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        returnValueCase_ = 3;
        return this;
      }
      /**
       * <code>.google.protobuf.Any result = 3;</code>
       */
      public Builder mergeResult(com.google.protobuf.Any value) {
        if (resultBuilder_ == null) {
          if (returnValueCase_ == 3 &&
              returnValue_ != com.google.protobuf.Any.getDefaultInstance()) {
            returnValue_ = com.google.protobuf.Any.newBuilder((com.google.protobuf.Any) returnValue_)
                .mergeFrom(value).buildPartial();
          } else {
            returnValue_ = value;
          }
          onChanged();
        } else {
          if (returnValueCase_ == 3) {
            resultBuilder_.mergeFrom(value);
          }
          resultBuilder_.setMessage(value);
        }
        returnValueCase_ = 3;
        return this;
      }
      /**
       * <code>.google.protobuf.Any result = 3;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          if (returnValueCase_ == 3) {
            returnValueCase_ = 0;
            returnValue_ = null;
            onChanged();
          }
        } else {
          if (returnValueCase_ == 3) {
            returnValueCase_ = 0;
            returnValue_ = null;
          }
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Any result = 3;</code>
       */
      public com.google.protobuf.Any.Builder getResultBuilder() {
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any result = 3;</code>
       */
      public com.google.protobuf.AnyOrBuilder getResultOrBuilder() {
        if ((returnValueCase_ == 3) && (resultBuilder_ != null)) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          if (returnValueCase_ == 3) {
            return (com.google.protobuf.Any) returnValue_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any result = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          if (!(returnValueCase_ == 3)) {
            returnValue_ = com.google.protobuf.Any.getDefaultInstance();
          }
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  (com.google.protobuf.Any) returnValue_,
                  getParentForChildren(),
                  isClean());
          returnValue_ = null;
        }
        returnValueCase_ = 3;
        onChanged();;
        return resultBuilder_;
      }

      /**
       * <code>string errorMessage = 4;</code>
       * @return The errorMessage.
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = "";
        if (returnValueCase_ == 4) {
          ref = returnValue_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (returnValueCase_ == 4) {
            returnValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errorMessage = 4;</code>
       * @return The bytes for errorMessage.
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = "";
        if (returnValueCase_ == 4) {
          ref = returnValue_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (returnValueCase_ == 4) {
            returnValue_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorMessage = 4;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  returnValueCase_ = 4;
        returnValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errorMessage = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        if (returnValueCase_ == 4) {
          returnValueCase_ = 0;
          returnValue_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string errorMessage = 4;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        returnValueCase_ = 4;
        returnValue_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.dousi.codec.Response)
    }

    // @@protoc_insertion_point(class_scope:org.dousi.codec.Response)
    private static final com.yunhui.fir.rpc.proto.FirRpcProtocol.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yunhui.fir.rpc.proto.FirRpcProtocol.Response();
    }

    public static com.yunhui.fir.rpc.proto.FirRpcProtocol.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yunhui.fir.rpc.proto.FirRpcProtocol.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_dousi_codec_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_dousi_codec_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_dousi_codec_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_dousi_codec_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rfir_rpc.proto\022\017org.dousi.codec\032\031google" +
      "/protobuf/any.proto\"k\n\007Request\022\021\n\treques" +
      "tId\030\001 \001(\003\022\025\n\rinterfaceName\030\002 \001(\t\022\022\n\nmeth" +
      "odName\030\003 \001(\t\022\"\n\004args\030\005 \003(\0132\024.google.prot" +
      "obuf.Any\"\230\001\n\010Response\022\021\n\trequestId\030\001 \001(\003" +
      "\022*\n\006status\030\002 \001(\0162\032.org.dousi.codec.RpcSt" +
      "atus\022&\n\006result\030\003 \001(\0132\024.google.protobuf.A" +
      "nyH\000\022\026\n\014errorMessage\030\004 \001(\tH\000B\r\n\013returnVa" +
      "lue*5\n\tRpcStatus\022\006\n\002OK\020\000\022\017\n\013OUTER_ERROR\020" +
      "\001\022\017\n\013INNER_ERROR\020\002B*\n\030com.yunhui.fir.rpc" +
      ".protoB\016FirRpcProtocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_org_dousi_codec_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_dousi_codec_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_dousi_codec_Request_descriptor,
        new java.lang.String[] { "RequestId", "InterfaceName", "MethodName", "Args", });
    internal_static_org_dousi_codec_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_dousi_codec_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_dousi_codec_Response_descriptor,
        new java.lang.String[] { "RequestId", "Status", "Result", "ErrorMessage", "ReturnValue", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
